aws_region         = "eu-central-1"
vpc_name           = "backend-vpc"
subnet_name        = "backend-public-subnet"
availability_zone  = "eu-central-1a"
instance_type      = "t3.micro"
key_name           = "learn"                          
instance_name      = "backend-instance"
user_data_script   = "scripts/backend_init.sh"
