name: Deploy Infrastructure

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy_ecr_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Apply ECR
        uses: ./.github/workflows/terraform-infra.yml
        with:
          action: apply
          component: ecr

      - name: Build Docker Images
        uses: ./.github/workflows/docker-build-push.yml

  deploy_backend:
    needs: deploy_ecr_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Apply Backend
        uses: ./.github/workflows/terraform-infra.yml
        with:
          action: apply
          component: backend

  deploy_frontend_and_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Frontend
        uses: ./.github/workflows/terraform-infra.yml
        with:
          action: apply
          component: frontend

      - name: Sync S3
        uses: ./.github/workflows/s3-sync.yml
