name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "you want to confirm your action: 'YES' or 'NO'"
        required: true
        type: string
  workflow_call:
    inputs:
      confirm:
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.check.outputs.allowed }}
    steps:
      - id: check
        run: |
          if [ "${{ inputs.confirm }}" != "YES" ]; then
            echo "allowed=false" >> $GITHUB_OUTPUT
          else
            echo "allowed=true" >> $GITHUB_OUTPUT
          fi

  cleanup:
    if: needs.guard.outputs.allowed == 'true'
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup ECR
        uses: ./.github/workflows/cleanup-ecr.yml
      - name: Cleanup S3
        uses: ./.github/workflows/s3-cleanup.yml

  destroy:
    if: needs.guard.outputs.allowed == 'true'
    needs: cleanup
    strategy:
      matrix:
        component: [ecr, backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Destroy ${{ matrix.component }}
        uses: ./.github/workflows/terraform-infra.yml
        with:
          action: destroy
          component: ${{ matrix.component }}
