name: Deploy Infrastructure

on:
  workflow_call:
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
    inputs:
      S3_BUCKET_NAME:
        required: true
        type: string

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply_ecr:
    uses: ./.github/workflows/terraform-infra.yml
    with:
      action: apply
      component: ecr
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  build_docker:
    uses: ./.github/workflows/build-and-push.yml
    needs: apply_ecr
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  apply_backend:
    uses: ./.github/workflows/terraform-infra.yml
    needs: build_docker
    with:
      action: apply
      component: backend
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  apply_frontend:
    uses: ./.github/workflows/terraform-infra.yml
    with:
      action: apply
      component: frontend
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  sync_s3:
    uses: ./.github/workflows/s3-sync.yml
    needs: apply_frontend
    inputs:
      S3_BUCKET_NAME: ${{ inputs.S3_BUCKET_NAME }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
