name: Full Destroy Pipeline

on:
  workflow_dispatch:

jobs:
  cleanup_artifacts:
    name: Cleanup ECR Images and S3
    runs-on: ubuntu-latest
    steps:
      - name: Clean ECR
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: cleanup-ecr.yml
          ref: main

      - name: Clean S3 Bucket
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: s3-cleanup.yml
          ref: main

  destroy_infrastructure:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest
    needs: cleanup_artifacts
    strategy:
      matrix:
        component: [ecr, backend, frontend]
    steps:
      - name: Destroy ${{ matrix.component }}
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: terraform-infra.yml
          ref: main
          inputs:
            action: destroy
            component: ${{ matrix.component }}
