name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "you want to confirm your action: 'YES' or 'NO'"
        required: true
        type: string

  workflow_call:
    inputs:
      confirm:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      S3_BUCKET_NAME:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      allowed: ${{ steps.check.outputs.allowed }}
    steps:
      - id: check
        run: |
          if [ "${{ inputs.confirm }}" != "YES" ]; then
            echo "allowed=false" >> $GITHUB_OUTPUT
          else
            echo "allowed=true" >> $GITHUB_OUTPUT
          fi

  #  cleanup_ecr:
  #   if: needs.guard.outputs.allowed == 'true'
  #   needs: guard
  #   uses: ./.github/workflows/cleanup-ecr.yml
  #   secrets:
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  # cleanup_s3:
  #   if: needs.guard.outputs.allowed == 'true'
  #   needs: guard
  #   uses: ./.github/workflows/s3-cleanup.yml
  #   secrets:
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  #     S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

  destroy:
    if: needs.guard.outputs.allowed == 'true'
    strategy:
      matrix:
        component: [ecr, backend, frontend]
    uses: ./.github/workflows/terraform-infra.yml
    with:
      action: destroy
      component: ${{ matrix.component }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

