name: Deploy Infrastructure

on:
  workflow_call:
  workflow_dispatch:

jobs:
  apply_ecr:
    uses: ./.github/workflows/terraform-infra.yml
    with:
      action: apply
      component: ecr

  build_docker:
    uses: ./.github/workflows/build-and-push.yml
    needs: apply_ecr

  apply_backend:
    uses: ./.github/workflows/terraform-infra.yml
    needs: build_docker
    with:
      action: apply
      component: backend

  apply_frontend:
    uses: ./.github/workflows/terraform-infra.yml
    with:
      action: apply
      component: frontend

  sync_s3:
    uses: ./.github/workflows/s3-sync.yml
    needs: apply_frontend
