name: Main Controller

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  trigger_deploy:
    uses: ./.github/workflows/infra-deploy.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      S3_BUCKET_NAME: ${{ secrets.FRONTEND_BUCKET_NAME }}

  wait_confirmed:
    name: Await manual approval before destroy
    runs-on: ubuntu-latest
    needs: trigger_deploy
    environment:
      name: approve-destroy
    outputs:
      confirmed: YES
    steps:
      - name: Approval received
        run: echo "Approval granted. Continuing..."

  trigger_destroy:
    needs: [trigger_deploy, wait_confirmed]
    uses: ./.github/workflows/infra-destroy.yml
    with:
      confirm: ${{ needs.wait_confirmed.outputs.confirmed }}
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      S3_BUCKET_NAME: ${{ secrets.FRONTEND_BUCKET_NAME }}
