name: Main Controller

on:
  push:
    branches:
      - main

jobs:
  trigger_deploy:
    name: Run Full Deploy Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: infra/deploy.yml
          ref: main

  trigger_destroy:
    name: Run Full Destroy Workflow
    runs-on: ubuntu-latest
    needs: trigger_deploy
    if: always()
    steps:
      - name: Trigger Destroy
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: infra/destroy.yml
          ref: main
